### ISSUE TITLE
Source maps having wrong paths

### ISSUE THREAD

**Issue by TheSHEEEP** [capacitor-community/electron#46] opened 2020-07-30 07:06 UTC
**Describe the bug**
I am developing a cross-platform application, and part of that is using @capacitor-community/electron for desktop.
The build and export itself works fine, and the electron application is functioning, but I cannot get the source maps to work.

I am updating the electron build like this:
`ionic cap sync`

And then run it by going to the electron directory and:
`npm run build && electron ./`

It seems to me that the .map files are just blindly copied from root/build/static/js to root/electron/app/static/js.
Naturally, the paths inside of the .map files won’t work in that location, as an additional “…/” (or even “…/…/”?) would be required.

The errors all look like this:

`devtools failed to load sourcemap could not load content for “capacitor-electron://-/static/js/16.45739f90.chunk.js.map”`

Is there a way to tell ionic (or capacitor) to change the paths so that the source maps will work with the electron target?
I'm not entirely sure if this is a bug or something additional I'd need to do to make it work properly.

**Desktop (please complete the following information):**

- OS: Manjaro Linux

**Comment by IT-MikeS** [comment] 2020-07-30 13:55
First, if you are using the `@capacitor-community/electron` please use the capacitor cli features of Capacitor v2.3.0+, for example `npx cap sync @capactior-community/electron`

As for the source map issue, what kind of project are you build (ionic angular/react, vuejs, ect..)?

**Comment by coreyjv** [comment] 2020-07-30 15:26
I experience this with an Ionic react app.

**Comment by IT-MikeS** [comment] 2020-07-30 16:51
This stems from an issue with Electron itself which may be inherently from a Chrome v80+ bug.

Read more here: https://github.com/electron/electron/issues/22996

**Comment by TheSHEEEP** [comment] 2020-07-30 19:46
I also experience this with an Ionic react app.

**Comment by TheSHEEEP** [comment] 2020-07-30 19:51
@IT-MikeS However, I don't think this is the error I am seeing. 
In the one you linked, Electron is unable to find a correct path.

In my case, the path itself is incorrect, because the .map files are actually created by ionic (I assume?) and then just copied to their new destination in the `electron` folder. In their new locations, their paths are not correct anymore.

I'll try with the suggested CLI tomorrow. And I'll also try to manually correct the paths to be sure that is the issue.

**Comment by IT-MikeS** [comment] 2020-07-30 19:58
What I did to recreate the issue is to create a basic starter app through the ionic cli `ionic start testapp tabs --type=react`.

I do get the warning about the source maps in dev tools, they are warnings and the app functions correctly without the maps, and the paths of mine are correct `capacitor-electron://-/static/js/27.f5e6c67c.chunk.js.map` but electron still can not resolve them. This is due to that bug/issue I linked. 

If you are getting something else, would it be possible to post up a repo or even screen captures of the issue?

**Comment by TheSHEEEP** [comment] 2020-07-31 06:21
I think there might be a misunderstanding here.

The error message doesn't say that the .map file cannot be found. The path `capacitor-electron://-/static/js/27.f5e6c67c.chunk.js.map` is correct (assuming that capacitor-electron://-/ leads to root/electron/app).
However, the path inside of the .map file is incorrect.

For example, one of my .map files begins like this:  
`{"version":3,"sources":["../node_modules/@ionic/core/dist/esm-es5/swipe-back-0a6a44c8.js"] ...`
That path, `"../node_modules/@ionic/core/dist/esm-es5/swipe-back-0a6a44c8.js"`, works if you assume the root to be the working directory.
However, it does not work if the working directory is root/electron, as that would require the path to become `"../../node_modules/..."`.

The error says `could not load content for ...` - it doesn't say that it cannot find the file itself.

**Comment by TheSHEEEP** [comment] 2020-07-31 06:51
Either way, I did adjust some of the paths inside of the .map files to point to the correct location (assuming it starts looking in root/electron/app), but the error message remains the same.

While I do think there is an error here with the paths inside of the .map files, there is also the bug inside of Chromium itself which prevents loading of source-maps from custom schemes as you mentioned.
Both would have to be resolved, but one is obviously out of this repo's hands.

**Comment by dominicdesu** [comment] 2020-10-10 21:01
Having the same issue here (albeit with ionic-angular).
As a workaround I switched to 'cheap-module-eval-source-map' in webpack.

**Comment by wolfejw86** [comment] 2020-12-31 21:54
Downgrading electron all the way to version 7 removes the issue.  I'm a total noob to electron, do electron versions correlate with ChromeVXX versions?

**Comment by IT-MikeS** [comment] 2021-02-03 14:12
This is an issue in electron it self but should be resolved with the new versions, and will be part of v3 of the platform.

**Comment by IT-MikeS** [comment] 2021-05-04 15:17
This is resolved in v3 so I will close this for now

**Closed** 2021-05-04 15:16 UTC
Labels: external cause
